
package trng.imcs.soap.temp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LoanEligibilityService", targetNamespace = "http://www.example.org/LoanService/", wsdlLocation = "file:/F:/MS/Eclipse/LoanWS/src/main/resources/WSDL/LoanService.wsdl")
public class LoanEligibilityService_Service
    extends Service
{

    private final static URL LOANELIGIBILITYSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOANELIGIBILITYSERVICE_EXCEPTION;
    private final static QName LOANELIGIBILITYSERVICE_QNAME = new QName("http://www.example.org/LoanService/", "LoanEligibilityService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/F:/MS/Eclipse/LoanWS/src/main/resources/WSDL/LoanService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOANELIGIBILITYSERVICE_WSDL_LOCATION = url;
        LOANELIGIBILITYSERVICE_EXCEPTION = e;
    }

    public LoanEligibilityService_Service() {
        super(__getWsdlLocation(), LOANELIGIBILITYSERVICE_QNAME);
    }

    public LoanEligibilityService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOANELIGIBILITYSERVICE_QNAME, features);
    }

    public LoanEligibilityService_Service(URL wsdlLocation) {
        super(wsdlLocation, LOANELIGIBILITYSERVICE_QNAME);
    }

    public LoanEligibilityService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOANELIGIBILITYSERVICE_QNAME, features);
    }

    public LoanEligibilityService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoanEligibilityService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoanEligibilityService
     */
    @WebEndpoint(name = "LoanServiceSOAP")
    public LoanEligibilityService getLoanServiceSOAP() {
        return super.getPort(new QName("http://www.example.org/LoanService/", "LoanServiceSOAP"), LoanEligibilityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoanEligibilityService
     */
    @WebEndpoint(name = "LoanServiceSOAP")
    public LoanEligibilityService getLoanServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/LoanService/", "LoanServiceSOAP"), LoanEligibilityService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOANELIGIBILITYSERVICE_EXCEPTION!= null) {
            throw LOANELIGIBILITYSERVICE_EXCEPTION;
        }
        return LOANELIGIBILITYSERVICE_WSDL_LOCATION;
    }

}
